Adding branch based env vars

diff --git a/.github/workflows/aws-tags.yml b/.github/workflows/aws-tags.yml
--- a/.github/workflows/aws-tags.yml
+++ b/.github/workflows/aws-tags.yml
@@ -52,26 +52,26 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v2
 
-#    - name: Set environment variables
-#      id: set-env-vars
-#      run: |
-#        if [[ GITHUB_REF_NAME -eq "main"]]; then
-#          echo "Setting up env vars for Prod"
-#          APPLICATION_ENV=prod
-#          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
-#          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
-#        elif [[ GITHUB_REF_NAME -eq "staging"]]; then
-#          echo "Setting up env vars for Staging"
-#          APPLICATION_ENV=staging
-#          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD_STAGING }}
-#          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD_STAGING }}
-#        else
-#          echo "ERROR - Unrecognised git ref. Couldn't set env vars."
-#          exit 1
-#        fi
+    - name: Set environment variables based on branch
+      id: set-env-vars
+      run: |
+        if [[ GITHUB_REF_NAME -eq "main"]]; then
+          echo "Setting up env vars for Prod"
+          APPLICATION_ENV=prod
+          AWS_ACCESS_KEY_ID=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
+        elif [[ GITHUB_REF_NAME -eq "staging"]]; then
+          echo "Setting up env vars for Staging"
+          APPLICATION_ENV=staging
+          AWS_ACCESS_KEY_ID=${{ secrets.STAGING_AWS_ACCESS_KEY_ID_PROD }}
+          AWS_SECRET_ACCESS_KEY=${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY_PROD }}
+        else
+          echo "ERROR - Unrecognised git ref. Couldn't set env vars."
+          exit 1
+        fi
 
     - name: Configure AWS credentials
-#      id: aws-login
+      id: aws-login
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -101,11 +101,11 @@ jobs:
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
 
-    - name: Render task definition from template
+    - name: Render Amazon ECS task definition from template in repo
       id: render-task-def
       uses: danielr1996/envsubst-action@1.0.0
-#      env:
-#        AWS_REGION: ${{ steps.aws-login.aws-account-id }}
+      env:
+        AWS_ACCOUNT_ID: ${{ steps.aws-login.aws-account-id }}
       with:
         input: ${{ env.ECS_TASK_DEFINITION_TEMPLATE }}
         output: ${{ env.ECS_TASK_DEFINITION_TEMPLATE }}.rendered.json
